### ISSUE TITLE
Can You do for Video format also

### ISSUE THREAD

**Issue by Varshithvhegde** [Asis2019/AsisYouTubeConverter#1]

**Comment by Asis2019** [comment]
Can you describe what you mean by video format? Otherwise this issue will be closed due to lack of clarity.

**Comment by Varshithvhegde** [comment]
I meant that t6his is downloading only audio right , how can you acheive it to download video also.

**Comment by Asis2019** [comment]
This app isn't ment for that, but if you wanted too all you should need to do is change the request options in this function:
https://github.com/Asis2019/AsisYouTubeConverter/blob/b65c4309fded1dd9e218909ec7ffbdd26d7b97d6/app/src/main/java/asis/youtubeconverter/download/DownloadService.java#L70-L92

**Comment by Varshithvhegde** [comment]
Ok Thankyou It was very helpful .
